/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-03-17 at 12:16:00 UTC 
 * Modify at your own risk.
 */

package de.hpi.cloud.news.model;

/**
 * Model definition for Article.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the HPI Cloud News API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Article extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> authorIds;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String content;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private URL link;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime publishDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String site;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Tag> tags;

  static {
    // hack to force ProGuard to consider Tag used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(Tag.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private URL thumbnail;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer viewCount;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getAuthorIds() {
    return authorIds;
  }

  /**
   * @param authorIds authorIds or {@code null} for none
   */
  public Article setAuthorIds(java.util.List<java.lang.String> authorIds) {
    this.authorIds = authorIds;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getContent() {
    return content;
  }

  /**
   * @param content content or {@code null} for none
   */
  public Article setContent(java.lang.String content) {
    this.content = content;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public Article setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Article setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public URL getLink() {
    return link;
  }

  /**
   * @param link link or {@code null} for none
   */
  public Article setLink(URL link) {
    this.link = link;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getPublishDate() {
    return publishDate;
  }

  /**
   * @param publishDate publishDate or {@code null} for none
   */
  public Article setPublishDate(com.google.api.client.util.DateTime publishDate) {
    this.publishDate = publishDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSite() {
    return site;
  }

  /**
   * @param site site or {@code null} for none
   */
  public Article setSite(java.lang.String site) {
    this.site = site;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Tag> getTags() {
    return tags;
  }

  /**
   * @param tags tags or {@code null} for none
   */
  public Article setTags(java.util.List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public URL getThumbnail() {
    return thumbnail;
  }

  /**
   * @param thumbnail thumbnail or {@code null} for none
   */
  public Article setThumbnail(URL thumbnail) {
    this.thumbnail = thumbnail;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public Article setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getViewCount() {
    return viewCount;
  }

  /**
   * @param viewCount viewCount or {@code null} for none
   */
  public Article setViewCount(java.lang.Integer viewCount) {
    this.viewCount = viewCount;
    return this;
  }

  @Override
  public Article set(String fieldName, Object value) {
    return (Article) super.set(fieldName, value);
  }

  @Override
  public Article clone() {
    return (Article) super.clone();
  }

}
