/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-03-17 at 12:16:00 UTC 
 * Modify at your own risk.
 */

package de.hpi.cloud.news.model;

/**
 * Model definition for URL.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the HPI Cloud News API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class URL extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String authority;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Object content;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer defaultPort;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String file;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String host;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String path;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer port;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String protocol;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String query;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ref;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userInfo;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAuthority() {
    return authority;
  }

  /**
   * @param authority authority or {@code null} for none
   */
  public URL setAuthority(java.lang.String authority) {
    this.authority = authority;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Object getContent() {
    return content;
  }

  /**
   * @param content content or {@code null} for none
   */
  public URL setContent(java.lang.Object content) {
    this.content = content;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDefaultPort() {
    return defaultPort;
  }

  /**
   * @param defaultPort defaultPort or {@code null} for none
   */
  public URL setDefaultPort(java.lang.Integer defaultPort) {
    this.defaultPort = defaultPort;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFile() {
    return file;
  }

  /**
   * @param file file or {@code null} for none
   */
  public URL setFile(java.lang.String file) {
    this.file = file;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getHost() {
    return host;
  }

  /**
   * @param host host or {@code null} for none
   */
  public URL setHost(java.lang.String host) {
    this.host = host;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPath() {
    return path;
  }

  /**
   * @param path path or {@code null} for none
   */
  public URL setPath(java.lang.String path) {
    this.path = path;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPort() {
    return port;
  }

  /**
   * @param port port or {@code null} for none
   */
  public URL setPort(java.lang.Integer port) {
    this.port = port;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProtocol() {
    return protocol;
  }

  /**
   * @param protocol protocol or {@code null} for none
   */
  public URL setProtocol(java.lang.String protocol) {
    this.protocol = protocol;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getQuery() {
    return query;
  }

  /**
   * @param query query or {@code null} for none
   */
  public URL setQuery(java.lang.String query) {
    this.query = query;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRef() {
    return ref;
  }

  /**
   * @param ref ref or {@code null} for none
   */
  public URL setRef(java.lang.String ref) {
    this.ref = ref;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserInfo() {
    return userInfo;
  }

  /**
   * @param userInfo userInfo or {@code null} for none
   */
  public URL setUserInfo(java.lang.String userInfo) {
    this.userInfo = userInfo;
    return this;
  }

  @Override
  public URL set(String fieldName, Object value) {
    return (URL) super.set(fieldName, value);
  }

  @Override
  public URL clone() {
    return (URL) super.clone();
  }

}
