// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/article.proto

package de.hpi.cloud.news.v1test;

public final class ArticleProto {
  private ArticleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hpi_cloud_news_v1test_Article_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hpi_cloud_news_v1test_Article_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hpi_cloud_news_v1test_Tag_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hpi_cloud_news_v1test_Tag_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#hpi/cloud/news/v1test/article.proto\022\025h" +
      "pi.cloud.news.v1test\032\037google/protobuf/ti" +
      "mestamp.proto\"\327\002\n\007Article\022\n\n\002id\030\001 \001(\t\0221\n" +
      "\004site\030\002 \001(\0162#.hpi.cloud.news.v1test.Arti" +
      "cle.Site\022\014\n\004link\030\003 \001(\t\022\r\n\005title\030\004 \001(\t\0220\n" +
      "\014publish_date\030\005 \001(\0132\032.google.protobuf.Ti" +
      "mestamp\022\021\n\tthumbnail\030\006 \001(\t\022\023\n\013descriptio" +
      "n\030\007 \001(\t\022\022\n\nauthor_ids\030\010 \003(\t\022\017\n\007content\030\t" +
      " \001(\t\022(\n\004tags\030\n \003(\0132\032.hpi.cloud.news.v1te" +
      "st.Tag\022\022\n\nview_count\030\020 \001(\r\"3\n\004Site\022\017\n\013UN" +
      "SPECIFIED\020\000\022\014\n\010HPI_NEWS\020\001\022\014\n\010HPI_MGZN\020\002\"" +
      "6\n\003Tag\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\025\n\rarti" +
      "cle_count\030\003 \001(\rB*\n\030de.hpi.cloud.news.v1t" +
      "estB\014ArticleProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_hpi_cloud_news_v1test_Article_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hpi_cloud_news_v1test_Article_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hpi_cloud_news_v1test_Article_descriptor,
        new java.lang.String[] { "Id", "Site", "Link", "Title", "PublishDate", "Thumbnail", "Description", "AuthorIds", "Content", "Tags", "ViewCount", });
    internal_static_hpi_cloud_news_v1test_Tag_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hpi_cloud_news_v1test_Tag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hpi_cloud_news_v1test_Tag_descriptor,
        new java.lang.String[] { "Id", "Name", "ArticleCount", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
