// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/article.proto

package de.hpi.cloud.news.v1test;

/**
 * <pre>
 * Represents a news article.
 * </pre>
 *
 * Protobuf type {@code hpi.cloud.news.v1test.Article}
 */
public  final class Article extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hpi.cloud.news.v1test.Article)
    ArticleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Article.newBuilder() to construct.
  private Article(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Article() {
    id_ = "";
    site_ = 0;
    link_ = "";
    title_ = "";
    thumbnail_ = "";
    description_ = "";
    authorIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    content_ = "";
    tags_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Article(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            site_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            link_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (publishDate_ != null) {
              subBuilder = publishDate_.toBuilder();
            }
            publishDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(publishDate_);
              publishDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            thumbnail_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000080) != 0)) {
              authorIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000080;
            }
            authorIds_.add(s);
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          case 82: {
            if (!((mutable_bitField0_ & 0x00000200) != 0)) {
              tags_ = new java.util.ArrayList<de.hpi.cloud.news.v1test.Tag>();
              mutable_bitField0_ |= 0x00000200;
            }
            tags_.add(
                input.readMessage(de.hpi.cloud.news.v1test.Tag.parser(), extensionRegistry));
            break;
          }
          case 128: {

            viewCount_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000080) != 0)) {
        authorIds_ = authorIds_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000200) != 0)) {
        tags_ = java.util.Collections.unmodifiableList(tags_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.hpi.cloud.news.v1test.ArticleProto.internal_static_hpi_cloud_news_v1test_Article_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.hpi.cloud.news.v1test.ArticleProto.internal_static_hpi_cloud_news_v1test_Article_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.hpi.cloud.news.v1test.Article.class, de.hpi.cloud.news.v1test.Article.Builder.class);
  }

  /**
   * <pre>
   * Site of an article.
   * </pre>
   *
   * Protobuf enum {@code hpi.cloud.news.v1test.Article.Site}
   */
  public enum Site
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Unspecified state.
     * </pre>
     *
     * <code>UNSPECIFIED = 0;</code>
     */
    UNSPECIFIED(0),
    /**
     * <pre>
     * The article originates from [hpi.de/medien/presseinformationen/news.html].
     * </pre>
     *
     * <code>HPI_NEWS = 1;</code>
     */
    HPI_NEWS(1),
    /**
     * <pre>
     * The article originates from [hpimgzn.de].
     * </pre>
     *
     * <code>HPI_MGZN = 2;</code>
     */
    HPI_MGZN(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Unspecified state.
     * </pre>
     *
     * <code>UNSPECIFIED = 0;</code>
     */
    public static final int UNSPECIFIED_VALUE = 0;
    /**
     * <pre>
     * The article originates from [hpi.de/medien/presseinformationen/news.html].
     * </pre>
     *
     * <code>HPI_NEWS = 1;</code>
     */
    public static final int HPI_NEWS_VALUE = 1;
    /**
     * <pre>
     * The article originates from [hpimgzn.de].
     * </pre>
     *
     * <code>HPI_MGZN = 2;</code>
     */
    public static final int HPI_MGZN_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Site valueOf(int value) {
      return forNumber(value);
    }

    public static Site forNumber(int value) {
      switch (value) {
        case 0: return UNSPECIFIED;
        case 1: return HPI_NEWS;
        case 2: return HPI_MGZN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Site>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Site> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Site>() {
            public Site findValueByNumber(int number) {
              return Site.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return de.hpi.cloud.news.v1test.Article.getDescriptor().getEnumTypes().get(0);
    }

    private static final Site[] VALUES = values();

    public static Site valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Site(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:hpi.cloud.news.v1test.Article.Site)
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * Required.
   *
   * The unique ID (across sites) of this article.
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required.
   *
   * The unique ID (across sites) of this article.
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SITE_FIELD_NUMBER = 2;
  private int site_;
  /**
   * <pre>
   * Required.
   *
   * Site of first appearance of this article.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
   */
  public int getSiteValue() {
    return site_;
  }
  /**
   * <pre>
   * Required.
   *
   * Site of first appearance of this article.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
   */
  public de.hpi.cloud.news.v1test.Article.Site getSite() {
    @SuppressWarnings("deprecation")
    de.hpi.cloud.news.v1test.Article.Site result = de.hpi.cloud.news.v1test.Article.Site.valueOf(site_);
    return result == null ? de.hpi.cloud.news.v1test.Article.Site.UNRECOGNIZED : result;
  }

  public static final int LINK_FIELD_NUMBER = 3;
  private volatile java.lang.Object link_;
  /**
   * <pre>
   * Required.
   *
   * A link to the original source.
   * </pre>
   *
   * <code>string link = 3;</code>
   */
  public java.lang.String getLink() {
    java.lang.Object ref = link_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      link_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required.
   *
   * A link to the original source.
   * </pre>
   *
   * <code>string link = 3;</code>
   */
  public com.google.protobuf.ByteString
      getLinkBytes() {
    java.lang.Object ref = link_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      link_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 4;
  private volatile java.lang.Object title_;
  /**
   * <pre>
   * Required.
   *
   * The title of this news article.
   * </pre>
   *
   * <code>string title = 4;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required.
   *
   * The title of this news article.
   * </pre>
   *
   * <code>string title = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUBLISH_DATE_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp publishDate_;
  /**
   * <pre>
   * Required.
   *
   * The publishing date.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp publish_date = 5;</code>
   */
  public boolean hasPublishDate() {
    return publishDate_ != null;
  }
  /**
   * <pre>
   * Required.
   *
   * The publishing date.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp publish_date = 5;</code>
   */
  public com.google.protobuf.Timestamp getPublishDate() {
    return publishDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : publishDate_;
  }
  /**
   * <pre>
   * Required.
   *
   * The publishing date.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp publish_date = 5;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getPublishDateOrBuilder() {
    return getPublishDate();
  }

  public static final int THUMBNAIL_FIELD_NUMBER = 6;
  private volatile java.lang.Object thumbnail_;
  /**
   * <pre>
   * Optional.
   *
   * A URL pointing to the thumbnail image.
   * </pre>
   *
   * <code>string thumbnail = 6;</code>
   */
  public java.lang.String getThumbnail() {
    java.lang.Object ref = thumbnail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      thumbnail_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional.
   *
   * A URL pointing to the thumbnail image.
   * </pre>
   *
   * <code>string thumbnail = 6;</code>
   */
  public com.google.protobuf.ByteString
      getThumbnailBytes() {
    java.lang.Object ref = thumbnail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      thumbnail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 7;
  private volatile java.lang.Object description_;
  /**
   * <pre>
   * Required.
   *
   * A short text summarizing this article. Recommended for a preview.
   * </pre>
   *
   * <code>string description = 7;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required.
   *
   * A short text summarizing this article. Recommended for a preview.
   * </pre>
   *
   * <code>string description = 7;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHOR_IDS_FIELD_NUMBER = 8;
  private com.google.protobuf.LazyStringList authorIds_;
  /**
   * <pre>
   * Optional.
   *
   * IDs of the author(s).
   * </pre>
   *
   * <code>repeated string author_ids = 8;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getAuthorIdsList() {
    return authorIds_;
  }
  /**
   * <pre>
   * Optional.
   *
   * IDs of the author(s).
   * </pre>
   *
   * <code>repeated string author_ids = 8;</code>
   */
  public int getAuthorIdsCount() {
    return authorIds_.size();
  }
  /**
   * <pre>
   * Optional.
   *
   * IDs of the author(s).
   * </pre>
   *
   * <code>repeated string author_ids = 8;</code>
   */
  public java.lang.String getAuthorIds(int index) {
    return authorIds_.get(index);
  }
  /**
   * <pre>
   * Optional.
   *
   * IDs of the author(s).
   * </pre>
   *
   * <code>repeated string author_ids = 8;</code>
   */
  public com.google.protobuf.ByteString
      getAuthorIdsBytes(int index) {
    return authorIds_.getByteString(index);
  }

  public static final int CONTENT_FIELD_NUMBER = 9;
  private volatile java.lang.Object content_;
  /**
   * <pre>
   * Required.
   *
   * The actual HTML-content of this article, i.e. the long variant of description.
   * </pre>
   *
   * <code>string content = 9;</code>
   */
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required.
   *
   * The actual HTML-content of this article, i.e. the long variant of description.
   * </pre>
   *
   * <code>string content = 9;</code>
   */
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 10;
  private java.util.List<de.hpi.cloud.news.v1test.Tag> tags_;
  /**
   * <pre>
   * Optional.
   *
   * Tags of this article.
   * </pre>
   *
   * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
   */
  public java.util.List<de.hpi.cloud.news.v1test.Tag> getTagsList() {
    return tags_;
  }
  /**
   * <pre>
   * Optional.
   *
   * Tags of this article.
   * </pre>
   *
   * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
   */
  public java.util.List<? extends de.hpi.cloud.news.v1test.TagOrBuilder> 
      getTagsOrBuilderList() {
    return tags_;
  }
  /**
   * <pre>
   * Optional.
   *
   * Tags of this article.
   * </pre>
   *
   * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <pre>
   * Optional.
   *
   * Tags of this article.
   * </pre>
   *
   * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
   */
  public de.hpi.cloud.news.v1test.Tag getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <pre>
   * Optional.
   *
   * Tags of this article.
   * </pre>
   *
   * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
   */
  public de.hpi.cloud.news.v1test.TagOrBuilder getTagsOrBuilder(
      int index) {
    return tags_.get(index);
  }

  public static final int VIEW_COUNT_FIELD_NUMBER = 16;
  private int viewCount_;
  /**
   * <pre>
   * Optional.
   *
   * The number of times this article was viewed.
   * </pre>
   *
   * <code>uint32 view_count = 16;</code>
   */
  public int getViewCount() {
    return viewCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (site_ != de.hpi.cloud.news.v1test.Article.Site.UNSPECIFIED.getNumber()) {
      output.writeEnum(2, site_);
    }
    if (!getLinkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, link_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, title_);
    }
    if (publishDate_ != null) {
      output.writeMessage(5, getPublishDate());
    }
    if (!getThumbnailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, thumbnail_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, description_);
    }
    for (int i = 0; i < authorIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, authorIds_.getRaw(i));
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, content_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      output.writeMessage(10, tags_.get(i));
    }
    if (viewCount_ != 0) {
      output.writeUInt32(16, viewCount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (site_ != de.hpi.cloud.news.v1test.Article.Site.UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, site_);
    }
    if (!getLinkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, link_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, title_);
    }
    if (publishDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getPublishDate());
    }
    if (!getThumbnailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, thumbnail_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, description_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < authorIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(authorIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAuthorIdsList().size();
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, content_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, tags_.get(i));
    }
    if (viewCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(16, viewCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.hpi.cloud.news.v1test.Article)) {
      return super.equals(obj);
    }
    de.hpi.cloud.news.v1test.Article other = (de.hpi.cloud.news.v1test.Article) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (site_ != other.site_) return false;
    if (!getLink()
        .equals(other.getLink())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (hasPublishDate() != other.hasPublishDate()) return false;
    if (hasPublishDate()) {
      if (!getPublishDate()
          .equals(other.getPublishDate())) return false;
    }
    if (!getThumbnail()
        .equals(other.getThumbnail())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getAuthorIdsList()
        .equals(other.getAuthorIdsList())) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (getViewCount()
        != other.getViewCount()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + SITE_FIELD_NUMBER;
    hash = (53 * hash) + site_;
    hash = (37 * hash) + LINK_FIELD_NUMBER;
    hash = (53 * hash) + getLink().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    if (hasPublishDate()) {
      hash = (37 * hash) + PUBLISH_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getPublishDate().hashCode();
    }
    hash = (37 * hash) + THUMBNAIL_FIELD_NUMBER;
    hash = (53 * hash) + getThumbnail().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (getAuthorIdsCount() > 0) {
      hash = (37 * hash) + AUTHOR_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorIdsList().hashCode();
    }
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    hash = (37 * hash) + VIEW_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getViewCount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.hpi.cloud.news.v1test.Article parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.Article parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.Article parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.Article parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.Article parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.Article parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.Article parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.Article parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.Article parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.Article parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.Article parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.Article parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.hpi.cloud.news.v1test.Article prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents a news article.
   * </pre>
   *
   * Protobuf type {@code hpi.cloud.news.v1test.Article}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hpi.cloud.news.v1test.Article)
      de.hpi.cloud.news.v1test.ArticleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.hpi.cloud.news.v1test.ArticleProto.internal_static_hpi_cloud_news_v1test_Article_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.hpi.cloud.news.v1test.ArticleProto.internal_static_hpi_cloud_news_v1test_Article_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.hpi.cloud.news.v1test.Article.class, de.hpi.cloud.news.v1test.Article.Builder.class);
    }

    // Construct using de.hpi.cloud.news.v1test.Article.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTagsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      site_ = 0;

      link_ = "";

      title_ = "";

      if (publishDateBuilder_ == null) {
        publishDate_ = null;
      } else {
        publishDate_ = null;
        publishDateBuilder_ = null;
      }
      thumbnail_ = "";

      description_ = "";

      authorIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000080);
      content_ = "";

      if (tagsBuilder_ == null) {
        tags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
      } else {
        tagsBuilder_.clear();
      }
      viewCount_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.hpi.cloud.news.v1test.ArticleProto.internal_static_hpi_cloud_news_v1test_Article_descriptor;
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.Article getDefaultInstanceForType() {
      return de.hpi.cloud.news.v1test.Article.getDefaultInstance();
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.Article build() {
      de.hpi.cloud.news.v1test.Article result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.Article buildPartial() {
      de.hpi.cloud.news.v1test.Article result = new de.hpi.cloud.news.v1test.Article(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.site_ = site_;
      result.link_ = link_;
      result.title_ = title_;
      if (publishDateBuilder_ == null) {
        result.publishDate_ = publishDate_;
      } else {
        result.publishDate_ = publishDateBuilder_.build();
      }
      result.thumbnail_ = thumbnail_;
      result.description_ = description_;
      if (((bitField0_ & 0x00000080) != 0)) {
        authorIds_ = authorIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000080);
      }
      result.authorIds_ = authorIds_;
      result.content_ = content_;
      if (tagsBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0)) {
          tags_ = java.util.Collections.unmodifiableList(tags_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.tags_ = tags_;
      } else {
        result.tags_ = tagsBuilder_.build();
      }
      result.viewCount_ = viewCount_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.hpi.cloud.news.v1test.Article) {
        return mergeFrom((de.hpi.cloud.news.v1test.Article)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.hpi.cloud.news.v1test.Article other) {
      if (other == de.hpi.cloud.news.v1test.Article.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.site_ != 0) {
        setSiteValue(other.getSiteValue());
      }
      if (!other.getLink().isEmpty()) {
        link_ = other.link_;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (other.hasPublishDate()) {
        mergePublishDate(other.getPublishDate());
      }
      if (!other.getThumbnail().isEmpty()) {
        thumbnail_ = other.thumbnail_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.authorIds_.isEmpty()) {
        if (authorIds_.isEmpty()) {
          authorIds_ = other.authorIds_;
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          ensureAuthorIdsIsMutable();
          authorIds_.addAll(other.authorIds_);
        }
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (tagsBuilder_ == null) {
        if (!other.tags_.isEmpty()) {
          if (tags_.isEmpty()) {
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureTagsIsMutable();
            tags_.addAll(other.tags_);
          }
          onChanged();
        }
      } else {
        if (!other.tags_.isEmpty()) {
          if (tagsBuilder_.isEmpty()) {
            tagsBuilder_.dispose();
            tagsBuilder_ = null;
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00000200);
            tagsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTagsFieldBuilder() : null;
          } else {
            tagsBuilder_.addAllMessages(other.tags_);
          }
        }
      }
      if (other.getViewCount() != 0) {
        setViewCount(other.getViewCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      de.hpi.cloud.news.v1test.Article parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (de.hpi.cloud.news.v1test.Article) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * Required.
     *
     * The unique ID (across sites) of this article.
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * The unique ID (across sites) of this article.
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * The unique ID (across sites) of this article.
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The unique ID (across sites) of this article.
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The unique ID (across sites) of this article.
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private int site_ = 0;
    /**
     * <pre>
     * Required.
     *
     * Site of first appearance of this article.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
     */
    public int getSiteValue() {
      return site_;
    }
    /**
     * <pre>
     * Required.
     *
     * Site of first appearance of this article.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
     */
    public Builder setSiteValue(int value) {
      site_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * Site of first appearance of this article.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
     */
    public de.hpi.cloud.news.v1test.Article.Site getSite() {
      @SuppressWarnings("deprecation")
      de.hpi.cloud.news.v1test.Article.Site result = de.hpi.cloud.news.v1test.Article.Site.valueOf(site_);
      return result == null ? de.hpi.cloud.news.v1test.Article.Site.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Required.
     *
     * Site of first appearance of this article.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
     */
    public Builder setSite(de.hpi.cloud.news.v1test.Article.Site value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      site_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * Site of first appearance of this article.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
     */
    public Builder clearSite() {
      
      site_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object link_ = "";
    /**
     * <pre>
     * Required.
     *
     * A link to the original source.
     * </pre>
     *
     * <code>string link = 3;</code>
     */
    public java.lang.String getLink() {
      java.lang.Object ref = link_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        link_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * A link to the original source.
     * </pre>
     *
     * <code>string link = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLinkBytes() {
      java.lang.Object ref = link_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * A link to the original source.
     * </pre>
     *
     * <code>string link = 3;</code>
     */
    public Builder setLink(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      link_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * A link to the original source.
     * </pre>
     *
     * <code>string link = 3;</code>
     */
    public Builder clearLink() {
      
      link_ = getDefaultInstance().getLink();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * A link to the original source.
     * </pre>
     *
     * <code>string link = 3;</code>
     */
    public Builder setLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      link_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <pre>
     * Required.
     *
     * The title of this news article.
     * </pre>
     *
     * <code>string title = 4;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * The title of this news article.
     * </pre>
     *
     * <code>string title = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * The title of this news article.
     * </pre>
     *
     * <code>string title = 4;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The title of this news article.
     * </pre>
     *
     * <code>string title = 4;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The title of this news article.
     * </pre>
     *
     * <code>string title = 4;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp publishDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> publishDateBuilder_;
    /**
     * <pre>
     * Required.
     *
     * The publishing date.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_date = 5;</code>
     */
    public boolean hasPublishDate() {
      return publishDateBuilder_ != null || publishDate_ != null;
    }
    /**
     * <pre>
     * Required.
     *
     * The publishing date.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_date = 5;</code>
     */
    public com.google.protobuf.Timestamp getPublishDate() {
      if (publishDateBuilder_ == null) {
        return publishDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : publishDate_;
      } else {
        return publishDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Required.
     *
     * The publishing date.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_date = 5;</code>
     */
    public Builder setPublishDate(com.google.protobuf.Timestamp value) {
      if (publishDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        publishDate_ = value;
        onChanged();
      } else {
        publishDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The publishing date.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_date = 5;</code>
     */
    public Builder setPublishDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (publishDateBuilder_ == null) {
        publishDate_ = builderForValue.build();
        onChanged();
      } else {
        publishDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The publishing date.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_date = 5;</code>
     */
    public Builder mergePublishDate(com.google.protobuf.Timestamp value) {
      if (publishDateBuilder_ == null) {
        if (publishDate_ != null) {
          publishDate_ =
            com.google.protobuf.Timestamp.newBuilder(publishDate_).mergeFrom(value).buildPartial();
        } else {
          publishDate_ = value;
        }
        onChanged();
      } else {
        publishDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The publishing date.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_date = 5;</code>
     */
    public Builder clearPublishDate() {
      if (publishDateBuilder_ == null) {
        publishDate_ = null;
        onChanged();
      } else {
        publishDate_ = null;
        publishDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The publishing date.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_date = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getPublishDateBuilder() {
      
      onChanged();
      return getPublishDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Required.
     *
     * The publishing date.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_date = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getPublishDateOrBuilder() {
      if (publishDateBuilder_ != null) {
        return publishDateBuilder_.getMessageOrBuilder();
      } else {
        return publishDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : publishDate_;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * The publishing date.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_date = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getPublishDateFieldBuilder() {
      if (publishDateBuilder_ == null) {
        publishDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getPublishDate(),
                getParentForChildren(),
                isClean());
        publishDate_ = null;
      }
      return publishDateBuilder_;
    }

    private java.lang.Object thumbnail_ = "";
    /**
     * <pre>
     * Optional.
     *
     * A URL pointing to the thumbnail image.
     * </pre>
     *
     * <code>string thumbnail = 6;</code>
     */
    public java.lang.String getThumbnail() {
      java.lang.Object ref = thumbnail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        thumbnail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional.
     *
     * A URL pointing to the thumbnail image.
     * </pre>
     *
     * <code>string thumbnail = 6;</code>
     */
    public com.google.protobuf.ByteString
        getThumbnailBytes() {
      java.lang.Object ref = thumbnail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        thumbnail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional.
     *
     * A URL pointing to the thumbnail image.
     * </pre>
     *
     * <code>string thumbnail = 6;</code>
     */
    public Builder setThumbnail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      thumbnail_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * A URL pointing to the thumbnail image.
     * </pre>
     *
     * <code>string thumbnail = 6;</code>
     */
    public Builder clearThumbnail() {
      
      thumbnail_ = getDefaultInstance().getThumbnail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * A URL pointing to the thumbnail image.
     * </pre>
     *
     * <code>string thumbnail = 6;</code>
     */
    public Builder setThumbnailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      thumbnail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * Required.
     *
     * A short text summarizing this article. Recommended for a preview.
     * </pre>
     *
     * <code>string description = 7;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * A short text summarizing this article. Recommended for a preview.
     * </pre>
     *
     * <code>string description = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * A short text summarizing this article. Recommended for a preview.
     * </pre>
     *
     * <code>string description = 7;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * A short text summarizing this article. Recommended for a preview.
     * </pre>
     *
     * <code>string description = 7;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * A short text summarizing this article. Recommended for a preview.
     * </pre>
     *
     * <code>string description = 7;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList authorIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAuthorIdsIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        authorIds_ = new com.google.protobuf.LazyStringArrayList(authorIds_);
        bitField0_ |= 0x00000080;
       }
    }
    /**
     * <pre>
     * Optional.
     *
     * IDs of the author(s).
     * </pre>
     *
     * <code>repeated string author_ids = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAuthorIdsList() {
      return authorIds_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Optional.
     *
     * IDs of the author(s).
     * </pre>
     *
     * <code>repeated string author_ids = 8;</code>
     */
    public int getAuthorIdsCount() {
      return authorIds_.size();
    }
    /**
     * <pre>
     * Optional.
     *
     * IDs of the author(s).
     * </pre>
     *
     * <code>repeated string author_ids = 8;</code>
     */
    public java.lang.String getAuthorIds(int index) {
      return authorIds_.get(index);
    }
    /**
     * <pre>
     * Optional.
     *
     * IDs of the author(s).
     * </pre>
     *
     * <code>repeated string author_ids = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorIdsBytes(int index) {
      return authorIds_.getByteString(index);
    }
    /**
     * <pre>
     * Optional.
     *
     * IDs of the author(s).
     * </pre>
     *
     * <code>repeated string author_ids = 8;</code>
     */
    public Builder setAuthorIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthorIdsIsMutable();
      authorIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * IDs of the author(s).
     * </pre>
     *
     * <code>repeated string author_ids = 8;</code>
     */
    public Builder addAuthorIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthorIdsIsMutable();
      authorIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * IDs of the author(s).
     * </pre>
     *
     * <code>repeated string author_ids = 8;</code>
     */
    public Builder addAllAuthorIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureAuthorIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, authorIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * IDs of the author(s).
     * </pre>
     *
     * <code>repeated string author_ids = 8;</code>
     */
    public Builder clearAuthorIds() {
      authorIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * IDs of the author(s).
     * </pre>
     *
     * <code>repeated string author_ids = 8;</code>
     */
    public Builder addAuthorIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAuthorIdsIsMutable();
      authorIds_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <pre>
     * Required.
     *
     * The actual HTML-content of this article, i.e. the long variant of description.
     * </pre>
     *
     * <code>string content = 9;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * The actual HTML-content of this article, i.e. the long variant of description.
     * </pre>
     *
     * <code>string content = 9;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * The actual HTML-content of this article, i.e. the long variant of description.
     * </pre>
     *
     * <code>string content = 9;</code>
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The actual HTML-content of this article, i.e. the long variant of description.
     * </pre>
     *
     * <code>string content = 9;</code>
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The actual HTML-content of this article, i.e. the long variant of description.
     * </pre>
     *
     * <code>string content = 9;</code>
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private java.util.List<de.hpi.cloud.news.v1test.Tag> tags_ =
      java.util.Collections.emptyList();
    private void ensureTagsIsMutable() {
      if (!((bitField0_ & 0x00000200) != 0)) {
        tags_ = new java.util.ArrayList<de.hpi.cloud.news.v1test.Tag>(tags_);
        bitField0_ |= 0x00000200;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.hpi.cloud.news.v1test.Tag, de.hpi.cloud.news.v1test.Tag.Builder, de.hpi.cloud.news.v1test.TagOrBuilder> tagsBuilder_;

    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public java.util.List<de.hpi.cloud.news.v1test.Tag> getTagsList() {
      if (tagsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tags_);
      } else {
        return tagsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public int getTagsCount() {
      if (tagsBuilder_ == null) {
        return tags_.size();
      } else {
        return tagsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public de.hpi.cloud.news.v1test.Tag getTags(int index) {
      if (tagsBuilder_ == null) {
        return tags_.get(index);
      } else {
        return tagsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public Builder setTags(
        int index, de.hpi.cloud.news.v1test.Tag value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagsIsMutable();
        tags_.set(index, value);
        onChanged();
      } else {
        tagsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public Builder setTags(
        int index, de.hpi.cloud.news.v1test.Tag.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.set(index, builderForValue.build());
        onChanged();
      } else {
        tagsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public Builder addTags(de.hpi.cloud.news.v1test.Tag value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
      } else {
        tagsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public Builder addTags(
        int index, de.hpi.cloud.news.v1test.Tag value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagsIsMutable();
        tags_.add(index, value);
        onChanged();
      } else {
        tagsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public Builder addTags(
        de.hpi.cloud.news.v1test.Tag.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.add(builderForValue.build());
        onChanged();
      } else {
        tagsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public Builder addTags(
        int index, de.hpi.cloud.news.v1test.Tag.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.add(index, builderForValue.build());
        onChanged();
      } else {
        tagsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public Builder addAllTags(
        java.lang.Iterable<? extends de.hpi.cloud.news.v1test.Tag> values) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tags_);
        onChanged();
      } else {
        tagsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public Builder clearTags() {
      if (tagsBuilder_ == null) {
        tags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
      } else {
        tagsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public Builder removeTags(int index) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.remove(index);
        onChanged();
      } else {
        tagsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public de.hpi.cloud.news.v1test.Tag.Builder getTagsBuilder(
        int index) {
      return getTagsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public de.hpi.cloud.news.v1test.TagOrBuilder getTagsOrBuilder(
        int index) {
      if (tagsBuilder_ == null) {
        return tags_.get(index);  } else {
        return tagsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public java.util.List<? extends de.hpi.cloud.news.v1test.TagOrBuilder> 
         getTagsOrBuilderList() {
      if (tagsBuilder_ != null) {
        return tagsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tags_);
      }
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public de.hpi.cloud.news.v1test.Tag.Builder addTagsBuilder() {
      return getTagsFieldBuilder().addBuilder(
          de.hpi.cloud.news.v1test.Tag.getDefaultInstance());
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public de.hpi.cloud.news.v1test.Tag.Builder addTagsBuilder(
        int index) {
      return getTagsFieldBuilder().addBuilder(
          index, de.hpi.cloud.news.v1test.Tag.getDefaultInstance());
    }
    /**
     * <pre>
     * Optional.
     *
     * Tags of this article.
     * </pre>
     *
     * <code>repeated .hpi.cloud.news.v1test.Tag tags = 10;</code>
     */
    public java.util.List<de.hpi.cloud.news.v1test.Tag.Builder> 
         getTagsBuilderList() {
      return getTagsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.hpi.cloud.news.v1test.Tag, de.hpi.cloud.news.v1test.Tag.Builder, de.hpi.cloud.news.v1test.TagOrBuilder> 
        getTagsFieldBuilder() {
      if (tagsBuilder_ == null) {
        tagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            de.hpi.cloud.news.v1test.Tag, de.hpi.cloud.news.v1test.Tag.Builder, de.hpi.cloud.news.v1test.TagOrBuilder>(
                tags_,
                ((bitField0_ & 0x00000200) != 0),
                getParentForChildren(),
                isClean());
        tags_ = null;
      }
      return tagsBuilder_;
    }

    private int viewCount_ ;
    /**
     * <pre>
     * Optional.
     *
     * The number of times this article was viewed.
     * </pre>
     *
     * <code>uint32 view_count = 16;</code>
     */
    public int getViewCount() {
      return viewCount_;
    }
    /**
     * <pre>
     * Optional.
     *
     * The number of times this article was viewed.
     * </pre>
     *
     * <code>uint32 view_count = 16;</code>
     */
    public Builder setViewCount(int value) {
      
      viewCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * The number of times this article was viewed.
     * </pre>
     *
     * <code>uint32 view_count = 16;</code>
     */
    public Builder clearViewCount() {
      
      viewCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hpi.cloud.news.v1test.Article)
  }

  // @@protoc_insertion_point(class_scope:hpi.cloud.news.v1test.Article)
  private static final de.hpi.cloud.news.v1test.Article DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.hpi.cloud.news.v1test.Article();
  }

  public static de.hpi.cloud.news.v1test.Article getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Article>
      PARSER = new com.google.protobuf.AbstractParser<Article>() {
    @java.lang.Override
    public Article parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Article(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Article> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Article> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.hpi.cloud.news.v1test.Article getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

