// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/author.proto

package de.hpi.cloud.news.v1test;

/**
 * <pre>
 * Represents the Author (wrapper around person) of an article.
 *
 * *Note: An instance is related to a specific site, so e.g. postCount is not global.*
 * </pre>
 *
 * Protobuf type {@code hpi.cloud.news.v1test.Author}
 */
public  final class Author extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hpi.cloud.news.v1test.Author)
    AuthorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Author.newBuilder() to construct.
  private Author(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Author() {
    id_ = "";
    personId_ = "";
    site_ = 0;
    link_ = "";
    description_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Author(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            personId_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            site_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            link_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 48: {

            postCount_ = input.readUInt32();
            break;
          }
          case 56: {

            commentCount_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.hpi.cloud.news.v1test.AuthorProto.internal_static_hpi_cloud_news_v1test_Author_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.hpi.cloud.news.v1test.AuthorProto.internal_static_hpi_cloud_news_v1test_Author_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.hpi.cloud.news.v1test.Author.class, de.hpi.cloud.news.v1test.Author.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * Required.
   *
   * The unique ID of this author.
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required.
   *
   * The unique ID of this author.
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERSON_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object personId_;
  /**
   * <pre>
   * Required.
   *
   * The ID of the person of this author.
   * </pre>
   *
   * <code>string person_id = 2;</code>
   */
  public java.lang.String getPersonId() {
    java.lang.Object ref = personId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      personId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required.
   *
   * The ID of the person of this author.
   * </pre>
   *
   * <code>string person_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPersonIdBytes() {
    java.lang.Object ref = personId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      personId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SITE_FIELD_NUMBER = 3;
  private int site_;
  /**
   * <pre>
   * Required.
   *
   * The site on which this author is registered.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 3;</code>
   */
  public int getSiteValue() {
    return site_;
  }
  /**
   * <pre>
   * Required.
   *
   * The site on which this author is registered.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 3;</code>
   */
  public de.hpi.cloud.news.v1test.Article.Site getSite() {
    @SuppressWarnings("deprecation")
    de.hpi.cloud.news.v1test.Article.Site result = de.hpi.cloud.news.v1test.Article.Site.valueOf(site_);
    return result == null ? de.hpi.cloud.news.v1test.Article.Site.UNRECOGNIZED : result;
  }

  public static final int LINK_FIELD_NUMBER = 4;
  private volatile java.lang.Object link_;
  /**
   * <pre>
   * Required.
   *
   * A URL pointing to the profile of this author on this site.
   * </pre>
   *
   * <code>string link = 4;</code>
   */
  public java.lang.String getLink() {
    java.lang.Object ref = link_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      link_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required.
   *
   * A URL pointing to the profile of this author on this site.
   * </pre>
   *
   * <code>string link = 4;</code>
   */
  public com.google.protobuf.ByteString
      getLinkBytes() {
    java.lang.Object ref = link_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      link_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 5;
  private volatile java.lang.Object description_;
  /**
   * <pre>
   * Optional.
   *
   * A description provided by the author about himself.
   * </pre>
   *
   * <code>string description = 5;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional.
   *
   * A description provided by the author about himself.
   * </pre>
   *
   * <code>string description = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POST_COUNT_FIELD_NUMBER = 6;
  private int postCount_;
  /**
   * <pre>
   * Optional.
   *
   * The number of posts.
   * </pre>
   *
   * <code>uint32 post_count = 6;</code>
   */
  public int getPostCount() {
    return postCount_;
  }

  public static final int COMMENT_COUNT_FIELD_NUMBER = 7;
  private int commentCount_;
  /**
   * <pre>
   * Optional.
   *
   * The number of comments.
   * </pre>
   *
   * <code>uint32 comment_count = 7;</code>
   */
  public int getCommentCount() {
    return commentCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getPersonIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, personId_);
    }
    if (site_ != de.hpi.cloud.news.v1test.Article.Site.UNSPECIFIED.getNumber()) {
      output.writeEnum(3, site_);
    }
    if (!getLinkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, link_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, description_);
    }
    if (postCount_ != 0) {
      output.writeUInt32(6, postCount_);
    }
    if (commentCount_ != 0) {
      output.writeUInt32(7, commentCount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getPersonIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, personId_);
    }
    if (site_ != de.hpi.cloud.news.v1test.Article.Site.UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, site_);
    }
    if (!getLinkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, link_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, description_);
    }
    if (postCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, postCount_);
    }
    if (commentCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, commentCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.hpi.cloud.news.v1test.Author)) {
      return super.equals(obj);
    }
    de.hpi.cloud.news.v1test.Author other = (de.hpi.cloud.news.v1test.Author) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getPersonId()
        .equals(other.getPersonId())) return false;
    if (site_ != other.site_) return false;
    if (!getLink()
        .equals(other.getLink())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (getPostCount()
        != other.getPostCount()) return false;
    if (getCommentCount()
        != other.getCommentCount()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + PERSON_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPersonId().hashCode();
    hash = (37 * hash) + SITE_FIELD_NUMBER;
    hash = (53 * hash) + site_;
    hash = (37 * hash) + LINK_FIELD_NUMBER;
    hash = (53 * hash) + getLink().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + POST_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getPostCount();
    hash = (37 * hash) + COMMENT_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCommentCount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.hpi.cloud.news.v1test.Author parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.Author parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.Author parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.Author parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.Author parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.Author parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.Author parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.Author parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.Author parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.Author parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.Author parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.Author parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.hpi.cloud.news.v1test.Author prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents the Author (wrapper around person) of an article.
   *
   * *Note: An instance is related to a specific site, so e.g. postCount is not global.*
   * </pre>
   *
   * Protobuf type {@code hpi.cloud.news.v1test.Author}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hpi.cloud.news.v1test.Author)
      de.hpi.cloud.news.v1test.AuthorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.hpi.cloud.news.v1test.AuthorProto.internal_static_hpi_cloud_news_v1test_Author_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.hpi.cloud.news.v1test.AuthorProto.internal_static_hpi_cloud_news_v1test_Author_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.hpi.cloud.news.v1test.Author.class, de.hpi.cloud.news.v1test.Author.Builder.class);
    }

    // Construct using de.hpi.cloud.news.v1test.Author.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      personId_ = "";

      site_ = 0;

      link_ = "";

      description_ = "";

      postCount_ = 0;

      commentCount_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.hpi.cloud.news.v1test.AuthorProto.internal_static_hpi_cloud_news_v1test_Author_descriptor;
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.Author getDefaultInstanceForType() {
      return de.hpi.cloud.news.v1test.Author.getDefaultInstance();
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.Author build() {
      de.hpi.cloud.news.v1test.Author result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.Author buildPartial() {
      de.hpi.cloud.news.v1test.Author result = new de.hpi.cloud.news.v1test.Author(this);
      result.id_ = id_;
      result.personId_ = personId_;
      result.site_ = site_;
      result.link_ = link_;
      result.description_ = description_;
      result.postCount_ = postCount_;
      result.commentCount_ = commentCount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.hpi.cloud.news.v1test.Author) {
        return mergeFrom((de.hpi.cloud.news.v1test.Author)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.hpi.cloud.news.v1test.Author other) {
      if (other == de.hpi.cloud.news.v1test.Author.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getPersonId().isEmpty()) {
        personId_ = other.personId_;
        onChanged();
      }
      if (other.site_ != 0) {
        setSiteValue(other.getSiteValue());
      }
      if (!other.getLink().isEmpty()) {
        link_ = other.link_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.getPostCount() != 0) {
        setPostCount(other.getPostCount());
      }
      if (other.getCommentCount() != 0) {
        setCommentCount(other.getCommentCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      de.hpi.cloud.news.v1test.Author parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (de.hpi.cloud.news.v1test.Author) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * Required.
     *
     * The unique ID of this author.
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * The unique ID of this author.
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * The unique ID of this author.
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The unique ID of this author.
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The unique ID of this author.
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object personId_ = "";
    /**
     * <pre>
     * Required.
     *
     * The ID of the person of this author.
     * </pre>
     *
     * <code>string person_id = 2;</code>
     */
    public java.lang.String getPersonId() {
      java.lang.Object ref = personId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * The ID of the person of this author.
     * </pre>
     *
     * <code>string person_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPersonIdBytes() {
      java.lang.Object ref = personId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * The ID of the person of this author.
     * </pre>
     *
     * <code>string person_id = 2;</code>
     */
    public Builder setPersonId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      personId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The ID of the person of this author.
     * </pre>
     *
     * <code>string person_id = 2;</code>
     */
    public Builder clearPersonId() {
      
      personId_ = getDefaultInstance().getPersonId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The ID of the person of this author.
     * </pre>
     *
     * <code>string person_id = 2;</code>
     */
    public Builder setPersonIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      personId_ = value;
      onChanged();
      return this;
    }

    private int site_ = 0;
    /**
     * <pre>
     * Required.
     *
     * The site on which this author is registered.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 3;</code>
     */
    public int getSiteValue() {
      return site_;
    }
    /**
     * <pre>
     * Required.
     *
     * The site on which this author is registered.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 3;</code>
     */
    public Builder setSiteValue(int value) {
      site_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The site on which this author is registered.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 3;</code>
     */
    public de.hpi.cloud.news.v1test.Article.Site getSite() {
      @SuppressWarnings("deprecation")
      de.hpi.cloud.news.v1test.Article.Site result = de.hpi.cloud.news.v1test.Article.Site.valueOf(site_);
      return result == null ? de.hpi.cloud.news.v1test.Article.Site.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Required.
     *
     * The site on which this author is registered.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 3;</code>
     */
    public Builder setSite(de.hpi.cloud.news.v1test.Article.Site value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      site_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * The site on which this author is registered.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 3;</code>
     */
    public Builder clearSite() {
      
      site_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object link_ = "";
    /**
     * <pre>
     * Required.
     *
     * A URL pointing to the profile of this author on this site.
     * </pre>
     *
     * <code>string link = 4;</code>
     */
    public java.lang.String getLink() {
      java.lang.Object ref = link_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        link_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * A URL pointing to the profile of this author on this site.
     * </pre>
     *
     * <code>string link = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLinkBytes() {
      java.lang.Object ref = link_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required.
     *
     * A URL pointing to the profile of this author on this site.
     * </pre>
     *
     * <code>string link = 4;</code>
     */
    public Builder setLink(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      link_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * A URL pointing to the profile of this author on this site.
     * </pre>
     *
     * <code>string link = 4;</code>
     */
    public Builder clearLink() {
      
      link_ = getDefaultInstance().getLink();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required.
     *
     * A URL pointing to the profile of this author on this site.
     * </pre>
     *
     * <code>string link = 4;</code>
     */
    public Builder setLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      link_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * Optional.
     *
     * A description provided by the author about himself.
     * </pre>
     *
     * <code>string description = 5;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional.
     *
     * A description provided by the author about himself.
     * </pre>
     *
     * <code>string description = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional.
     *
     * A description provided by the author about himself.
     * </pre>
     *
     * <code>string description = 5;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * A description provided by the author about himself.
     * </pre>
     *
     * <code>string description = 5;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * A description provided by the author about himself.
     * </pre>
     *
     * <code>string description = 5;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private int postCount_ ;
    /**
     * <pre>
     * Optional.
     *
     * The number of posts.
     * </pre>
     *
     * <code>uint32 post_count = 6;</code>
     */
    public int getPostCount() {
      return postCount_;
    }
    /**
     * <pre>
     * Optional.
     *
     * The number of posts.
     * </pre>
     *
     * <code>uint32 post_count = 6;</code>
     */
    public Builder setPostCount(int value) {
      
      postCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * The number of posts.
     * </pre>
     *
     * <code>uint32 post_count = 6;</code>
     */
    public Builder clearPostCount() {
      
      postCount_ = 0;
      onChanged();
      return this;
    }

    private int commentCount_ ;
    /**
     * <pre>
     * Optional.
     *
     * The number of comments.
     * </pre>
     *
     * <code>uint32 comment_count = 7;</code>
     */
    public int getCommentCount() {
      return commentCount_;
    }
    /**
     * <pre>
     * Optional.
     *
     * The number of comments.
     * </pre>
     *
     * <code>uint32 comment_count = 7;</code>
     */
    public Builder setCommentCount(int value) {
      
      commentCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * The number of comments.
     * </pre>
     *
     * <code>uint32 comment_count = 7;</code>
     */
    public Builder clearCommentCount() {
      
      commentCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hpi.cloud.news.v1test.Author)
  }

  // @@protoc_insertion_point(class_scope:hpi.cloud.news.v1test.Author)
  private static final de.hpi.cloud.news.v1test.Author DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.hpi.cloud.news.v1test.Author();
  }

  public static de.hpi.cloud.news.v1test.Author getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Author>
      PARSER = new com.google.protobuf.AbstractParser<Author>() {
    @java.lang.Override
    public Author parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Author(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Author> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Author> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.hpi.cloud.news.v1test.Author getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

