// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/author.proto

package de.hpi.cloud.news.v1test;

public final class AuthorProto {
  private AuthorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hpi_cloud_news_v1test_Author_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hpi_cloud_news_v1test_Author_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"hpi/cloud/news/v1test/author.proto\022\025hp" +
      "i.cloud.news.v1test\032#hpi/cloud/news/v1te" +
      "st/article.proto\"\250\001\n\006Author\022\n\n\002id\030\001 \001(\t\022" +
      "\021\n\tperson_id\030\002 \001(\t\0221\n\004site\030\003 \001(\0162#.hpi.c" +
      "loud.news.v1test.Article.Site\022\014\n\004link\030\004 " +
      "\001(\t\022\023\n\013description\030\005 \001(\t\022\022\n\npost_count\030\006" +
      " \001(\r\022\025\n\rcomment_count\030\007 \001(\rB)\n\030de.hpi.cl" +
      "oud.news.v1testB\013AuthorProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.hpi.cloud.news.v1test.ArticleProto.getDescriptor(),
        }, assigner);
    internal_static_hpi_cloud_news_v1test_Author_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hpi_cloud_news_v1test_Author_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hpi_cloud_news_v1test_Author_descriptor,
        new java.lang.String[] { "Id", "PersonId", "Site", "Link", "Description", "PostCount", "CommentCount", });
    de.hpi.cloud.news.v1test.ArticleProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
