// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/author.proto

package de.hpi.cloud.news.v1test;

public interface AuthorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hpi.cloud.news.v1test.Author)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required.
   *
   * The unique ID of this author.
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * Required.
   *
   * The unique ID of this author.
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Required.
   *
   * The ID of the person of this author.
   * </pre>
   *
   * <code>string person_id = 2;</code>
   */
  java.lang.String getPersonId();
  /**
   * <pre>
   * Required.
   *
   * The ID of the person of this author.
   * </pre>
   *
   * <code>string person_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getPersonIdBytes();

  /**
   * <pre>
   * Required.
   *
   * The site on which this author is registered.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 3;</code>
   */
  int getSiteValue();
  /**
   * <pre>
   * Required.
   *
   * The site on which this author is registered.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 3;</code>
   */
  de.hpi.cloud.news.v1test.Article.Site getSite();

  /**
   * <pre>
   * Required.
   *
   * A URL pointing to the profile of this author on this site.
   * </pre>
   *
   * <code>string link = 4;</code>
   */
  java.lang.String getLink();
  /**
   * <pre>
   * Required.
   *
   * A URL pointing to the profile of this author on this site.
   * </pre>
   *
   * <code>string link = 4;</code>
   */
  com.google.protobuf.ByteString
      getLinkBytes();

  /**
   * <pre>
   * Optional.
   *
   * A description provided by the author about himself.
   * </pre>
   *
   * <code>string description = 5;</code>
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Optional.
   *
   * A description provided by the author about himself.
   * </pre>
   *
   * <code>string description = 5;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * Optional.
   *
   * The number of posts.
   * </pre>
   *
   * <code>uint32 post_count = 6;</code>
   */
  int getPostCount();

  /**
   * <pre>
   * Optional.
   *
   * The number of comments.
   * </pre>
   *
   * <code>uint32 comment_count = 7;</code>
   */
  int getCommentCount();
}
