// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/news_service.proto

package de.hpi.cloud.news.v1test;

public interface GetArticleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hpi.cloud.news.v1test.GetArticleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required.
   *
   * The article ID.
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * Required.
   *
   * The article ID.
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
