// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/news_service.proto

package de.hpi.cloud.news.v1test;

/**
 * <pre>
 * Request message for listing articles using [ListArticles][hpi.cloud.news.v1test.NewsService.ListArticles].
 * </pre>
 *
 * Protobuf type {@code hpi.cloud.news.v1test.ListArticlesRequest}
 */
public  final class ListArticlesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hpi.cloud.news.v1test.ListArticlesRequest)
    ListArticlesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListArticlesRequest.newBuilder() to construct.
  private ListArticlesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListArticlesRequest() {
    site_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListArticlesRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            site_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListArticlesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListArticlesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.hpi.cloud.news.v1test.ListArticlesRequest.class, de.hpi.cloud.news.v1test.ListArticlesRequest.Builder.class);
  }

  public static final int SITE_FIELD_NUMBER = 1;
  private int site_;
  /**
   * <pre>
   * Optional.
   *
   *If specified, only articles from this site are returned.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 1;</code>
   */
  public int getSiteValue() {
    return site_;
  }
  /**
   * <pre>
   * Optional.
   *
   *If specified, only articles from this site are returned.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 1;</code>
   */
  public de.hpi.cloud.news.v1test.Article.Site getSite() {
    @SuppressWarnings("deprecation")
    de.hpi.cloud.news.v1test.Article.Site result = de.hpi.cloud.news.v1test.Article.Site.valueOf(site_);
    return result == null ? de.hpi.cloud.news.v1test.Article.Site.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (site_ != de.hpi.cloud.news.v1test.Article.Site.UNSPECIFIED.getNumber()) {
      output.writeEnum(1, site_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (site_ != de.hpi.cloud.news.v1test.Article.Site.UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, site_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.hpi.cloud.news.v1test.ListArticlesRequest)) {
      return super.equals(obj);
    }
    de.hpi.cloud.news.v1test.ListArticlesRequest other = (de.hpi.cloud.news.v1test.ListArticlesRequest) obj;

    if (site_ != other.site_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SITE_FIELD_NUMBER;
    hash = (53 * hash) + site_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.hpi.cloud.news.v1test.ListArticlesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.ListArticlesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListArticlesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.ListArticlesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListArticlesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.ListArticlesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListArticlesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.ListArticlesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListArticlesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.ListArticlesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListArticlesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.ListArticlesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.hpi.cloud.news.v1test.ListArticlesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message for listing articles using [ListArticles][hpi.cloud.news.v1test.NewsService.ListArticles].
   * </pre>
   *
   * Protobuf type {@code hpi.cloud.news.v1test.ListArticlesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hpi.cloud.news.v1test.ListArticlesRequest)
      de.hpi.cloud.news.v1test.ListArticlesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListArticlesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListArticlesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.hpi.cloud.news.v1test.ListArticlesRequest.class, de.hpi.cloud.news.v1test.ListArticlesRequest.Builder.class);
    }

    // Construct using de.hpi.cloud.news.v1test.ListArticlesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      site_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListArticlesRequest_descriptor;
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.ListArticlesRequest getDefaultInstanceForType() {
      return de.hpi.cloud.news.v1test.ListArticlesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.ListArticlesRequest build() {
      de.hpi.cloud.news.v1test.ListArticlesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.ListArticlesRequest buildPartial() {
      de.hpi.cloud.news.v1test.ListArticlesRequest result = new de.hpi.cloud.news.v1test.ListArticlesRequest(this);
      result.site_ = site_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.hpi.cloud.news.v1test.ListArticlesRequest) {
        return mergeFrom((de.hpi.cloud.news.v1test.ListArticlesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.hpi.cloud.news.v1test.ListArticlesRequest other) {
      if (other == de.hpi.cloud.news.v1test.ListArticlesRequest.getDefaultInstance()) return this;
      if (other.site_ != 0) {
        setSiteValue(other.getSiteValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      de.hpi.cloud.news.v1test.ListArticlesRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (de.hpi.cloud.news.v1test.ListArticlesRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int site_ = 0;
    /**
     * <pre>
     * Optional.
     *
     *If specified, only articles from this site are returned.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 1;</code>
     */
    public int getSiteValue() {
      return site_;
    }
    /**
     * <pre>
     * Optional.
     *
     *If specified, only articles from this site are returned.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 1;</code>
     */
    public Builder setSiteValue(int value) {
      site_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     *If specified, only articles from this site are returned.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 1;</code>
     */
    public de.hpi.cloud.news.v1test.Article.Site getSite() {
      @SuppressWarnings("deprecation")
      de.hpi.cloud.news.v1test.Article.Site result = de.hpi.cloud.news.v1test.Article.Site.valueOf(site_);
      return result == null ? de.hpi.cloud.news.v1test.Article.Site.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Optional.
     *
     *If specified, only articles from this site are returned.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 1;</code>
     */
    public Builder setSite(de.hpi.cloud.news.v1test.Article.Site value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      site_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     *If specified, only articles from this site are returned.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 1;</code>
     */
    public Builder clearSite() {
      
      site_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hpi.cloud.news.v1test.ListArticlesRequest)
  }

  // @@protoc_insertion_point(class_scope:hpi.cloud.news.v1test.ListArticlesRequest)
  private static final de.hpi.cloud.news.v1test.ListArticlesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.hpi.cloud.news.v1test.ListArticlesRequest();
  }

  public static de.hpi.cloud.news.v1test.ListArticlesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListArticlesRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListArticlesRequest>() {
    @java.lang.Override
    public ListArticlesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListArticlesRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListArticlesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListArticlesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.hpi.cloud.news.v1test.ListArticlesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

