// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/news_service.proto

package de.hpi.cloud.news.v1test;

public interface ListAuthorsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hpi.cloud.news.v1test.ListAuthorsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
   */
  java.util.List<de.hpi.cloud.news.v1test.Author> 
      getAuthorsList();
  /**
   * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
   */
  de.hpi.cloud.news.v1test.Author getAuthors(int index);
  /**
   * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
   */
  int getAuthorsCount();
  /**
   * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
   */
  java.util.List<? extends de.hpi.cloud.news.v1test.AuthorOrBuilder> 
      getAuthorsOrBuilderList();
  /**
   * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
   */
  de.hpi.cloud.news.v1test.AuthorOrBuilder getAuthorsOrBuilder(
      int index);
}
