// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/news_service.proto

package de.hpi.cloud.news.v1test;

/**
 * <pre>
 * Response message for listing authors using [ListAuthors][hpi.cloud.news.v1test.NewsService.ListAuthors].
 * </pre>
 *
 * Protobuf type {@code hpi.cloud.news.v1test.ListAuthorsResponse}
 */
public  final class ListAuthorsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hpi.cloud.news.v1test.ListAuthorsResponse)
    ListAuthorsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListAuthorsResponse.newBuilder() to construct.
  private ListAuthorsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListAuthorsResponse() {
    authors_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListAuthorsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              authors_ = new java.util.ArrayList<de.hpi.cloud.news.v1test.Author>();
              mutable_bitField0_ |= 0x00000001;
            }
            authors_.add(
                input.readMessage(de.hpi.cloud.news.v1test.Author.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        authors_ = java.util.Collections.unmodifiableList(authors_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListAuthorsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListAuthorsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.hpi.cloud.news.v1test.ListAuthorsResponse.class, de.hpi.cloud.news.v1test.ListAuthorsResponse.Builder.class);
  }

  public static final int AUTHORS_FIELD_NUMBER = 1;
  private java.util.List<de.hpi.cloud.news.v1test.Author> authors_;
  /**
   * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
   */
  public java.util.List<de.hpi.cloud.news.v1test.Author> getAuthorsList() {
    return authors_;
  }
  /**
   * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
   */
  public java.util.List<? extends de.hpi.cloud.news.v1test.AuthorOrBuilder> 
      getAuthorsOrBuilderList() {
    return authors_;
  }
  /**
   * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
   */
  public int getAuthorsCount() {
    return authors_.size();
  }
  /**
   * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
   */
  public de.hpi.cloud.news.v1test.Author getAuthors(int index) {
    return authors_.get(index);
  }
  /**
   * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
   */
  public de.hpi.cloud.news.v1test.AuthorOrBuilder getAuthorsOrBuilder(
      int index) {
    return authors_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < authors_.size(); i++) {
      output.writeMessage(1, authors_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < authors_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, authors_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.hpi.cloud.news.v1test.ListAuthorsResponse)) {
      return super.equals(obj);
    }
    de.hpi.cloud.news.v1test.ListAuthorsResponse other = (de.hpi.cloud.news.v1test.ListAuthorsResponse) obj;

    if (!getAuthorsList()
        .equals(other.getAuthorsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAuthorsCount() > 0) {
      hash = (37 * hash) + AUTHORS_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.hpi.cloud.news.v1test.ListAuthorsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.hpi.cloud.news.v1test.ListAuthorsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response message for listing authors using [ListAuthors][hpi.cloud.news.v1test.NewsService.ListAuthors].
   * </pre>
   *
   * Protobuf type {@code hpi.cloud.news.v1test.ListAuthorsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hpi.cloud.news.v1test.ListAuthorsResponse)
      de.hpi.cloud.news.v1test.ListAuthorsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListAuthorsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListAuthorsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.hpi.cloud.news.v1test.ListAuthorsResponse.class, de.hpi.cloud.news.v1test.ListAuthorsResponse.Builder.class);
    }

    // Construct using de.hpi.cloud.news.v1test.ListAuthorsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAuthorsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (authorsBuilder_ == null) {
        authors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        authorsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListAuthorsResponse_descriptor;
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.ListAuthorsResponse getDefaultInstanceForType() {
      return de.hpi.cloud.news.v1test.ListAuthorsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.ListAuthorsResponse build() {
      de.hpi.cloud.news.v1test.ListAuthorsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.ListAuthorsResponse buildPartial() {
      de.hpi.cloud.news.v1test.ListAuthorsResponse result = new de.hpi.cloud.news.v1test.ListAuthorsResponse(this);
      int from_bitField0_ = bitField0_;
      if (authorsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          authors_ = java.util.Collections.unmodifiableList(authors_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.authors_ = authors_;
      } else {
        result.authors_ = authorsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.hpi.cloud.news.v1test.ListAuthorsResponse) {
        return mergeFrom((de.hpi.cloud.news.v1test.ListAuthorsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.hpi.cloud.news.v1test.ListAuthorsResponse other) {
      if (other == de.hpi.cloud.news.v1test.ListAuthorsResponse.getDefaultInstance()) return this;
      if (authorsBuilder_ == null) {
        if (!other.authors_.isEmpty()) {
          if (authors_.isEmpty()) {
            authors_ = other.authors_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAuthorsIsMutable();
            authors_.addAll(other.authors_);
          }
          onChanged();
        }
      } else {
        if (!other.authors_.isEmpty()) {
          if (authorsBuilder_.isEmpty()) {
            authorsBuilder_.dispose();
            authorsBuilder_ = null;
            authors_ = other.authors_;
            bitField0_ = (bitField0_ & ~0x00000001);
            authorsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAuthorsFieldBuilder() : null;
          } else {
            authorsBuilder_.addAllMessages(other.authors_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      de.hpi.cloud.news.v1test.ListAuthorsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (de.hpi.cloud.news.v1test.ListAuthorsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<de.hpi.cloud.news.v1test.Author> authors_ =
      java.util.Collections.emptyList();
    private void ensureAuthorsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        authors_ = new java.util.ArrayList<de.hpi.cloud.news.v1test.Author>(authors_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.hpi.cloud.news.v1test.Author, de.hpi.cloud.news.v1test.Author.Builder, de.hpi.cloud.news.v1test.AuthorOrBuilder> authorsBuilder_;

    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public java.util.List<de.hpi.cloud.news.v1test.Author> getAuthorsList() {
      if (authorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(authors_);
      } else {
        return authorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public int getAuthorsCount() {
      if (authorsBuilder_ == null) {
        return authors_.size();
      } else {
        return authorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public de.hpi.cloud.news.v1test.Author getAuthors(int index) {
      if (authorsBuilder_ == null) {
        return authors_.get(index);
      } else {
        return authorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public Builder setAuthors(
        int index, de.hpi.cloud.news.v1test.Author value) {
      if (authorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAuthorsIsMutable();
        authors_.set(index, value);
        onChanged();
      } else {
        authorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public Builder setAuthors(
        int index, de.hpi.cloud.news.v1test.Author.Builder builderForValue) {
      if (authorsBuilder_ == null) {
        ensureAuthorsIsMutable();
        authors_.set(index, builderForValue.build());
        onChanged();
      } else {
        authorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public Builder addAuthors(de.hpi.cloud.news.v1test.Author value) {
      if (authorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAuthorsIsMutable();
        authors_.add(value);
        onChanged();
      } else {
        authorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public Builder addAuthors(
        int index, de.hpi.cloud.news.v1test.Author value) {
      if (authorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAuthorsIsMutable();
        authors_.add(index, value);
        onChanged();
      } else {
        authorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public Builder addAuthors(
        de.hpi.cloud.news.v1test.Author.Builder builderForValue) {
      if (authorsBuilder_ == null) {
        ensureAuthorsIsMutable();
        authors_.add(builderForValue.build());
        onChanged();
      } else {
        authorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public Builder addAuthors(
        int index, de.hpi.cloud.news.v1test.Author.Builder builderForValue) {
      if (authorsBuilder_ == null) {
        ensureAuthorsIsMutable();
        authors_.add(index, builderForValue.build());
        onChanged();
      } else {
        authorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public Builder addAllAuthors(
        java.lang.Iterable<? extends de.hpi.cloud.news.v1test.Author> values) {
      if (authorsBuilder_ == null) {
        ensureAuthorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, authors_);
        onChanged();
      } else {
        authorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public Builder clearAuthors() {
      if (authorsBuilder_ == null) {
        authors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        authorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public Builder removeAuthors(int index) {
      if (authorsBuilder_ == null) {
        ensureAuthorsIsMutable();
        authors_.remove(index);
        onChanged();
      } else {
        authorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public de.hpi.cloud.news.v1test.Author.Builder getAuthorsBuilder(
        int index) {
      return getAuthorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public de.hpi.cloud.news.v1test.AuthorOrBuilder getAuthorsOrBuilder(
        int index) {
      if (authorsBuilder_ == null) {
        return authors_.get(index);  } else {
        return authorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public java.util.List<? extends de.hpi.cloud.news.v1test.AuthorOrBuilder> 
         getAuthorsOrBuilderList() {
      if (authorsBuilder_ != null) {
        return authorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(authors_);
      }
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public de.hpi.cloud.news.v1test.Author.Builder addAuthorsBuilder() {
      return getAuthorsFieldBuilder().addBuilder(
          de.hpi.cloud.news.v1test.Author.getDefaultInstance());
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public de.hpi.cloud.news.v1test.Author.Builder addAuthorsBuilder(
        int index) {
      return getAuthorsFieldBuilder().addBuilder(
          index, de.hpi.cloud.news.v1test.Author.getDefaultInstance());
    }
    /**
     * <code>repeated .hpi.cloud.news.v1test.Author Authors = 1;</code>
     */
    public java.util.List<de.hpi.cloud.news.v1test.Author.Builder> 
         getAuthorsBuilderList() {
      return getAuthorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.hpi.cloud.news.v1test.Author, de.hpi.cloud.news.v1test.Author.Builder, de.hpi.cloud.news.v1test.AuthorOrBuilder> 
        getAuthorsFieldBuilder() {
      if (authorsBuilder_ == null) {
        authorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            de.hpi.cloud.news.v1test.Author, de.hpi.cloud.news.v1test.Author.Builder, de.hpi.cloud.news.v1test.AuthorOrBuilder>(
                authors_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        authors_ = null;
      }
      return authorsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hpi.cloud.news.v1test.ListAuthorsResponse)
  }

  // @@protoc_insertion_point(class_scope:hpi.cloud.news.v1test.ListAuthorsResponse)
  private static final de.hpi.cloud.news.v1test.ListAuthorsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.hpi.cloud.news.v1test.ListAuthorsResponse();
  }

  public static de.hpi.cloud.news.v1test.ListAuthorsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListAuthorsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListAuthorsResponse>() {
    @java.lang.Override
    public ListAuthorsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListAuthorsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListAuthorsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListAuthorsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.hpi.cloud.news.v1test.ListAuthorsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

