// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/news_service.proto

package de.hpi.cloud.news.v1test;

public interface ListAuthorsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hpi.cloud.news.v1test.ListAuthorsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional.
   *
   * If specified, only author instances of this person are returned.
   * </pre>
   *
   * <code>string person_id = 1;</code>
   */
  java.lang.String getPersonId();
  /**
   * <pre>
   * Optional.
   *
   * If specified, only author instances of this person are returned.
   * </pre>
   *
   * <code>string person_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getPersonIdBytes();

  /**
   * <pre>
   * Optional.
   *
   * If specified, only authors from this site are returned.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
   */
  int getSiteValue();
  /**
   * <pre>
   * Optional.
   *
   * If specified, only authors from this site are returned.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
   */
  de.hpi.cloud.news.v1test.Article.Site getSite();

  /**
   * <pre>
   * Optional.
   *
   * If specified, only authors of this article are returned.
   * </pre>
   *
   * <code>string article_id = 3;</code>
   */
  java.lang.String getArticleId();
  /**
   * <pre>
   * Optional.
   *
   * If specified, only authors of this article are returned.
   * </pre>
   *
   * <code>string article_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getArticleIdBytes();
}
