// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/news_service.proto

package de.hpi.cloud.news.v1test;

public interface ListArticlesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hpi.cloud.news.v1test.ListArticlesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional.
   *
   *If specified, only articles from this site are returned.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 1;</code>
   */
  int getSiteValue();
  /**
   * <pre>
   * Optional.
   *
   *If specified, only articles from this site are returned.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 1;</code>
   */
  de.hpi.cloud.news.v1test.Article.Site getSite();
}
