// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/news_service.proto

package de.hpi.cloud.news.v1test;

/**
 * <pre>
 * Request message for listing authors using [ListAuthors][hpi.cloud.news.v1test.NewsService.ListAuthors].
 * </pre>
 *
 * Protobuf type {@code hpi.cloud.news.v1test.ListAuthorsRequest}
 */
public  final class ListAuthorsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hpi.cloud.news.v1test.ListAuthorsRequest)
    ListAuthorsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListAuthorsRequest.newBuilder() to construct.
  private ListAuthorsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListAuthorsRequest() {
    personId_ = "";
    site_ = 0;
    articleId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListAuthorsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            personId_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            site_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            articleId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListAuthorsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListAuthorsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.hpi.cloud.news.v1test.ListAuthorsRequest.class, de.hpi.cloud.news.v1test.ListAuthorsRequest.Builder.class);
  }

  public static final int PERSON_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object personId_;
  /**
   * <pre>
   * Optional.
   *
   * If specified, only author instances of this person are returned.
   * </pre>
   *
   * <code>string person_id = 1;</code>
   */
  public java.lang.String getPersonId() {
    java.lang.Object ref = personId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      personId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional.
   *
   * If specified, only author instances of this person are returned.
   * </pre>
   *
   * <code>string person_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPersonIdBytes() {
    java.lang.Object ref = personId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      personId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SITE_FIELD_NUMBER = 2;
  private int site_;
  /**
   * <pre>
   * Optional.
   *
   * If specified, only authors from this site are returned.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
   */
  public int getSiteValue() {
    return site_;
  }
  /**
   * <pre>
   * Optional.
   *
   * If specified, only authors from this site are returned.
   * </pre>
   *
   * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
   */
  public de.hpi.cloud.news.v1test.Article.Site getSite() {
    @SuppressWarnings("deprecation")
    de.hpi.cloud.news.v1test.Article.Site result = de.hpi.cloud.news.v1test.Article.Site.valueOf(site_);
    return result == null ? de.hpi.cloud.news.v1test.Article.Site.UNRECOGNIZED : result;
  }

  public static final int ARTICLE_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object articleId_;
  /**
   * <pre>
   * Optional.
   *
   * If specified, only authors of this article are returned.
   * </pre>
   *
   * <code>string article_id = 3;</code>
   */
  public java.lang.String getArticleId() {
    java.lang.Object ref = articleId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      articleId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional.
   *
   * If specified, only authors of this article are returned.
   * </pre>
   *
   * <code>string article_id = 3;</code>
   */
  public com.google.protobuf.ByteString
      getArticleIdBytes() {
    java.lang.Object ref = articleId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      articleId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPersonIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, personId_);
    }
    if (site_ != de.hpi.cloud.news.v1test.Article.Site.UNSPECIFIED.getNumber()) {
      output.writeEnum(2, site_);
    }
    if (!getArticleIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, articleId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPersonIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, personId_);
    }
    if (site_ != de.hpi.cloud.news.v1test.Article.Site.UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, site_);
    }
    if (!getArticleIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, articleId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.hpi.cloud.news.v1test.ListAuthorsRequest)) {
      return super.equals(obj);
    }
    de.hpi.cloud.news.v1test.ListAuthorsRequest other = (de.hpi.cloud.news.v1test.ListAuthorsRequest) obj;

    if (!getPersonId()
        .equals(other.getPersonId())) return false;
    if (site_ != other.site_) return false;
    if (!getArticleId()
        .equals(other.getArticleId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PERSON_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPersonId().hashCode();
    hash = (37 * hash) + SITE_FIELD_NUMBER;
    hash = (53 * hash) + site_;
    hash = (37 * hash) + ARTICLE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getArticleId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.hpi.cloud.news.v1test.ListAuthorsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.hpi.cloud.news.v1test.ListAuthorsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.hpi.cloud.news.v1test.ListAuthorsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message for listing authors using [ListAuthors][hpi.cloud.news.v1test.NewsService.ListAuthors].
   * </pre>
   *
   * Protobuf type {@code hpi.cloud.news.v1test.ListAuthorsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hpi.cloud.news.v1test.ListAuthorsRequest)
      de.hpi.cloud.news.v1test.ListAuthorsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListAuthorsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListAuthorsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.hpi.cloud.news.v1test.ListAuthorsRequest.class, de.hpi.cloud.news.v1test.ListAuthorsRequest.Builder.class);
    }

    // Construct using de.hpi.cloud.news.v1test.ListAuthorsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      personId_ = "";

      site_ = 0;

      articleId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.hpi.cloud.news.v1test.NewsServiceProto.internal_static_hpi_cloud_news_v1test_ListAuthorsRequest_descriptor;
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.ListAuthorsRequest getDefaultInstanceForType() {
      return de.hpi.cloud.news.v1test.ListAuthorsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.ListAuthorsRequest build() {
      de.hpi.cloud.news.v1test.ListAuthorsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.hpi.cloud.news.v1test.ListAuthorsRequest buildPartial() {
      de.hpi.cloud.news.v1test.ListAuthorsRequest result = new de.hpi.cloud.news.v1test.ListAuthorsRequest(this);
      result.personId_ = personId_;
      result.site_ = site_;
      result.articleId_ = articleId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.hpi.cloud.news.v1test.ListAuthorsRequest) {
        return mergeFrom((de.hpi.cloud.news.v1test.ListAuthorsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.hpi.cloud.news.v1test.ListAuthorsRequest other) {
      if (other == de.hpi.cloud.news.v1test.ListAuthorsRequest.getDefaultInstance()) return this;
      if (!other.getPersonId().isEmpty()) {
        personId_ = other.personId_;
        onChanged();
      }
      if (other.site_ != 0) {
        setSiteValue(other.getSiteValue());
      }
      if (!other.getArticleId().isEmpty()) {
        articleId_ = other.articleId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      de.hpi.cloud.news.v1test.ListAuthorsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (de.hpi.cloud.news.v1test.ListAuthorsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object personId_ = "";
    /**
     * <pre>
     * Optional.
     *
     * If specified, only author instances of this person are returned.
     * </pre>
     *
     * <code>string person_id = 1;</code>
     */
    public java.lang.String getPersonId() {
      java.lang.Object ref = personId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional.
     *
     * If specified, only author instances of this person are returned.
     * </pre>
     *
     * <code>string person_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPersonIdBytes() {
      java.lang.Object ref = personId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional.
     *
     * If specified, only author instances of this person are returned.
     * </pre>
     *
     * <code>string person_id = 1;</code>
     */
    public Builder setPersonId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      personId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * If specified, only author instances of this person are returned.
     * </pre>
     *
     * <code>string person_id = 1;</code>
     */
    public Builder clearPersonId() {
      
      personId_ = getDefaultInstance().getPersonId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * If specified, only author instances of this person are returned.
     * </pre>
     *
     * <code>string person_id = 1;</code>
     */
    public Builder setPersonIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      personId_ = value;
      onChanged();
      return this;
    }

    private int site_ = 0;
    /**
     * <pre>
     * Optional.
     *
     * If specified, only authors from this site are returned.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
     */
    public int getSiteValue() {
      return site_;
    }
    /**
     * <pre>
     * Optional.
     *
     * If specified, only authors from this site are returned.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
     */
    public Builder setSiteValue(int value) {
      site_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * If specified, only authors from this site are returned.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
     */
    public de.hpi.cloud.news.v1test.Article.Site getSite() {
      @SuppressWarnings("deprecation")
      de.hpi.cloud.news.v1test.Article.Site result = de.hpi.cloud.news.v1test.Article.Site.valueOf(site_);
      return result == null ? de.hpi.cloud.news.v1test.Article.Site.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Optional.
     *
     * If specified, only authors from this site are returned.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
     */
    public Builder setSite(de.hpi.cloud.news.v1test.Article.Site value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      site_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * If specified, only authors from this site are returned.
     * </pre>
     *
     * <code>.hpi.cloud.news.v1test.Article.Site site = 2;</code>
     */
    public Builder clearSite() {
      
      site_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object articleId_ = "";
    /**
     * <pre>
     * Optional.
     *
     * If specified, only authors of this article are returned.
     * </pre>
     *
     * <code>string article_id = 3;</code>
     */
    public java.lang.String getArticleId() {
      java.lang.Object ref = articleId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        articleId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional.
     *
     * If specified, only authors of this article are returned.
     * </pre>
     *
     * <code>string article_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getArticleIdBytes() {
      java.lang.Object ref = articleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        articleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional.
     *
     * If specified, only authors of this article are returned.
     * </pre>
     *
     * <code>string article_id = 3;</code>
     */
    public Builder setArticleId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      articleId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * If specified, only authors of this article are returned.
     * </pre>
     *
     * <code>string article_id = 3;</code>
     */
    public Builder clearArticleId() {
      
      articleId_ = getDefaultInstance().getArticleId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional.
     *
     * If specified, only authors of this article are returned.
     * </pre>
     *
     * <code>string article_id = 3;</code>
     */
    public Builder setArticleIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      articleId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hpi.cloud.news.v1test.ListAuthorsRequest)
  }

  // @@protoc_insertion_point(class_scope:hpi.cloud.news.v1test.ListAuthorsRequest)
  private static final de.hpi.cloud.news.v1test.ListAuthorsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.hpi.cloud.news.v1test.ListAuthorsRequest();
  }

  public static de.hpi.cloud.news.v1test.ListAuthorsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListAuthorsRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListAuthorsRequest>() {
    @java.lang.Override
    public ListAuthorsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListAuthorsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListAuthorsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListAuthorsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.hpi.cloud.news.v1test.ListAuthorsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

