// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/news_service.proto

package de.hpi.cloud.news.v1test;

public interface ListArticlesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hpi.cloud.news.v1test.ListArticlesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .hpi.cloud.news.v1test.Article articles = 1;</code>
   */
  java.util.List<de.hpi.cloud.news.v1test.Article> 
      getArticlesList();
  /**
   * <code>repeated .hpi.cloud.news.v1test.Article articles = 1;</code>
   */
  de.hpi.cloud.news.v1test.Article getArticles(int index);
  /**
   * <code>repeated .hpi.cloud.news.v1test.Article articles = 1;</code>
   */
  int getArticlesCount();
  /**
   * <code>repeated .hpi.cloud.news.v1test.Article articles = 1;</code>
   */
  java.util.List<? extends de.hpi.cloud.news.v1test.ArticleOrBuilder> 
      getArticlesOrBuilderList();
  /**
   * <code>repeated .hpi.cloud.news.v1test.Article articles = 1;</code>
   */
  de.hpi.cloud.news.v1test.ArticleOrBuilder getArticlesOrBuilder(
      int index);
}
