// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/news_service.proto

package de.hpi.cloud.news.v1test;

public final class NewsServiceProto {
  private NewsServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hpi_cloud_news_v1test_ListArticlesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hpi_cloud_news_v1test_ListArticlesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hpi_cloud_news_v1test_ListArticlesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hpi_cloud_news_v1test_ListArticlesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hpi_cloud_news_v1test_GetArticleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hpi_cloud_news_v1test_GetArticleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hpi_cloud_news_v1test_ListAuthorsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hpi_cloud_news_v1test_ListAuthorsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hpi_cloud_news_v1test_ListAuthorsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hpi_cloud_news_v1test_ListAuthorsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hpi_cloud_news_v1test_GetAuthorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hpi_cloud_news_v1test_GetAuthorRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(hpi/cloud/news/v1test/news_service.pro" +
      "to\022\025hpi.cloud.news.v1test\032#hpi/cloud/new" +
      "s/v1test/article.proto\032\"hpi/cloud/news/v" +
      "1test/author.proto\"H\n\023ListArticlesReques" +
      "t\0221\n\004site\030\001 \001(\0162#.hpi.cloud.news.v1test." +
      "Article.Site\"H\n\024ListArticlesResponse\0220\n\010" +
      "articles\030\001 \003(\0132\036.hpi.cloud.news.v1test.A" +
      "rticle\"\037\n\021GetArticleRequest\022\n\n\002id\030\001 \001(\t\"" +
      "n\n\022ListAuthorsRequest\022\021\n\tperson_id\030\001 \001(\t" +
      "\0221\n\004site\030\002 \001(\0162#.hpi.cloud.news.v1test.A" +
      "rticle.Site\022\022\n\narticle_id\030\003 \001(\t\"E\n\023ListA" +
      "uthorsResponse\022.\n\007Authors\030\001 \003(\0132\035.hpi.cl" +
      "oud.news.v1test.Author\"\036\n\020GetAuthorReque" +
      "st\022\n\n\002id\030\001 \001(\t2\211\003\n\013NewsService\022g\n\014ListAr" +
      "ticles\022*.hpi.cloud.news.v1test.ListArtic" +
      "lesRequest\032+.hpi.cloud.news.v1test.ListA" +
      "rticlesResponse\022V\n\nGetArticle\022(.hpi.clou" +
      "d.news.v1test.GetArticleRequest\032\036.hpi.cl" +
      "oud.news.v1test.Article\022d\n\013ListAuthors\022)" +
      ".hpi.cloud.news.v1test.ListAuthorsReques" +
      "t\032*.hpi.cloud.news.v1test.ListAuthorsRes" +
      "ponse\022S\n\tGetAuthor\022\'.hpi.cloud.news.v1te" +
      "st.GetAuthorRequest\032\035.hpi.cloud.news.v1t" +
      "est.AuthorB.\n\030de.hpi.cloud.news.v1testB\020" +
      "NewsServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.hpi.cloud.news.v1test.ArticleProto.getDescriptor(),
          de.hpi.cloud.news.v1test.AuthorProto.getDescriptor(),
        }, assigner);
    internal_static_hpi_cloud_news_v1test_ListArticlesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hpi_cloud_news_v1test_ListArticlesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hpi_cloud_news_v1test_ListArticlesRequest_descriptor,
        new java.lang.String[] { "Site", });
    internal_static_hpi_cloud_news_v1test_ListArticlesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hpi_cloud_news_v1test_ListArticlesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hpi_cloud_news_v1test_ListArticlesResponse_descriptor,
        new java.lang.String[] { "Articles", });
    internal_static_hpi_cloud_news_v1test_GetArticleRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_hpi_cloud_news_v1test_GetArticleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hpi_cloud_news_v1test_GetArticleRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_hpi_cloud_news_v1test_ListAuthorsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_hpi_cloud_news_v1test_ListAuthorsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hpi_cloud_news_v1test_ListAuthorsRequest_descriptor,
        new java.lang.String[] { "PersonId", "Site", "ArticleId", });
    internal_static_hpi_cloud_news_v1test_ListAuthorsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_hpi_cloud_news_v1test_ListAuthorsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hpi_cloud_news_v1test_ListAuthorsResponse_descriptor,
        new java.lang.String[] { "Authors", });
    internal_static_hpi_cloud_news_v1test_GetAuthorRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_hpi_cloud_news_v1test_GetAuthorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hpi_cloud_news_v1test_GetAuthorRequest_descriptor,
        new java.lang.String[] { "Id", });
    de.hpi.cloud.news.v1test.ArticleProto.getDescriptor();
    de.hpi.cloud.news.v1test.AuthorProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
