// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/news/v1test/article.proto

package de.hpi.cloud.news.v1test;

public interface TagOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hpi.cloud.news.v1test.Tag)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required.
   *
   * The unique ID of this tag.
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * Required.
   *
   * The unique ID of this tag.
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Required.
   *
   * The name of this tag.
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * Required.
   *
   * The name of this tag.
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Required.
   *
   * The number of articles tagged with this tag.
   * </pre>
   *
   * <code>uint32 article_count = 3;</code>
   */
  int getArticleCount();
}
