// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpi/cloud/common/v1test/person.proto

package de.hpi.cloud.common.v1test;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hpi_cloud_common_v1test_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hpi_cloud_common_v1test_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hpi_cloud_common_v1test_Person_Name_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hpi_cloud_common_v1test_Person_Name_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hpi_cloud_common_v1test_Person_Gender_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hpi_cloud_common_v1test_Person_Gender_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$hpi/cloud/common/v1test/person.proto\022\027" +
      "hpi.cloud.common.v1test\032\026google/type/dat" +
      "e.proto\032-hpi/cloud/common/v1test/social_" +
      "profiles.proto\"\264\n\n\006Person\022\n\n\002id\030\001 \001(\t\022;\n" +
      "\013person_name\030\002 \001(\0132$.hpi.cloud.common.v1" +
      "test.Person.NameH\000\022\033\n\021organization_name\030" +
      "\003 \001(\tH\000\0226\n\006gender\030\004 \001(\0132&.hpi.cloud.comm" +
      "on.v1test.Person.Gender\022(\n\rdate_of_birth" +
      "\030\005 \001(\0132\021.google.type.Date\022\027\n\017email_addre" +
      "sses\030\006 \003(\t\022\016\n\006avatar\030\007 \001(\t\022\020\n\010homepage\030\010" +
      " \001(\t\022@\n\017social_profiles\030\t \001(\0132\'.hpi.clou" +
      "d.common.v1test.SocialProfiles\032q\n\004Name\022\016" +
      "\n\006prefix\030\001 \001(\t\022\021\n\tfirstName\030\002 \001(\t\022\022\n\nmid" +
      "dleName\030\003 \001(\t\022\020\n\010lastName\030\004 \001(\t\022\016\n\006suffi" +
      "x\030\005 \001(\t\022\020\n\010nickname\030\006 \001(\t\032\351\006\n\006Gender\022J\n\014" +
      "known_gender\030\001 \001(\01622.hpi.cloud.common.v1" +
      "test.Person.Gender.KnownGenderH\000\022\027\n\rcust" +
      "om_gender\030\002 \001(\tH\000\022E\n\013refer_to_as\030\003 \001(\01620" +
      ".hpi.cloud.common.v1test.Person.Gender.R" +
      "eferToAs\"\377\004\n\013KnownGender\022\021\n\rNOT_APLICABL" +
      "E\020\000\022\n\n\006FEMALE\020\001\022\010\n\004MALE\020\002\022\014\n\010DONT_SAY\020\003\022" +
      "\013\n\007NEITHER\020\004\022\013\n\007AGENDER\020\005\022\r\n\tANDROGYNE\020\020" +
      "\022\021\n\rHERMAPHRODITE\020\021\022\014\n\010BIGENDER\020\022\022\r\n\tTRI" +
      "GENDER\020\023\022\023\n\017GENDER_VARIABLE\020\024\022\017\n\013GENDERQ" +
      "UEER\020\025\022\r\n\tPANGENDER\020\026\022\014\n\010INTERSEX\020\027\022\021\n\rG" +
      "ENDER_BENDER\020\030\022\017\n\013TRANS_WOMAN\020d\022\020\n\014TRANS" +
      "_FEMALE\020e\022\r\n\tTRANS_MAN\020f\022\016\n\nTRANS_MALE\020g" +
      "\022\026\n\022TRANSGENDER_FEMALE\020n\022\024\n\020TRANSGENDER_" +
      "MALE\020o\022\026\n\022TRANSSEXUAL_FEMALE\020x\022\024\n\020TRANSS" +
      "EXUAL_MALE\020y\022\010\n\003FTM\020\202\001\022\010\n\003MTF\020\203\001\022\021\n\014THIR" +
      "D_GENDER\020\240\006\022\022\n\rFOURTH_GENDER\020\241\006\022\026\n\021APACH" +
      "E_HELICOPTER\020\350\007\022\013\n\006MINION\020\351\007\022 \n\033MOUNTAIN" +
      "_GORILLA_PINOT_NOIR\020\352\007\022\016\n\tPINEAPPLE\020\353\007\022\022" +
      "\n\rLIVER_SAUSAGE\020\354\007\022\037\n\032MALE_AFTER9_WITHOU" +
      "T_COFFEE\020\355\007\022%\n FEMALE_CAME_FROM_EAST_WEN" +
      "T_SOUTH\020\356\007\"\'\n\tReferToAs\022\010\n\004THEM\020\000\022\007\n\003HER" +
      "\020\001\022\007\n\003HIM\020\002B\010\n\006genderB\006\n\004nameB+\n\032de.hpi." +
      "cloud.common.v1testB\013PersonProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.type.DateProto.getDescriptor(),
          de.hpi.cloud.common.v1test.SocialProfilesProto.getDescriptor(),
        }, assigner);
    internal_static_hpi_cloud_common_v1test_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hpi_cloud_common_v1test_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hpi_cloud_common_v1test_Person_descriptor,
        new java.lang.String[] { "Id", "PersonName", "OrganizationName", "Gender", "DateOfBirth", "EmailAddresses", "Avatar", "Homepage", "SocialProfiles", "Name", });
    internal_static_hpi_cloud_common_v1test_Person_Name_descriptor =
      internal_static_hpi_cloud_common_v1test_Person_descriptor.getNestedTypes().get(0);
    internal_static_hpi_cloud_common_v1test_Person_Name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hpi_cloud_common_v1test_Person_Name_descriptor,
        new java.lang.String[] { "Prefix", "FirstName", "MiddleName", "LastName", "Suffix", "Nickname", });
    internal_static_hpi_cloud_common_v1test_Person_Gender_descriptor =
      internal_static_hpi_cloud_common_v1test_Person_descriptor.getNestedTypes().get(1);
    internal_static_hpi_cloud_common_v1test_Person_Gender_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hpi_cloud_common_v1test_Person_Gender_descriptor,
        new java.lang.String[] { "KnownGender", "CustomGender", "ReferToAs", "Gender", });
    com.google.type.DateProto.getDescriptor();
    de.hpi.cloud.common.v1test.SocialProfilesProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
